server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    password: 1234
    #    url: jdbc:postgresql://localhost:5432/registration
    url: jdbc:mysql://localhost:3307/schoolpay
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
