server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    password: b2e3902a597c0ffdce141ac94be42650c2b4984621d22425051ec4f53886a99f
     url: postgres://ec2-52-206-182-219.compute-1.amazonaws.com:5432/dcb7g00rnbjf3r
#    url: ec2-52-206-182-219.compute-1.amazonaws.com:5432/schoolpay
    username: vlatuhyculvugb
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

  mail:

    host: smtp.gmail.com
    port: 587
    username: benardwamache@gmail.com
    password: mjhpxaqrhtteilyw

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          #connectiontimeout: 5000
          #timeout: 3000
          #writetimeout: 5000

